[project]
name = "rewardpilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Divya Sahni", email = "divyasahni87@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "openai>=3.13.0",
    "pinecone>=10.0.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.57",
]

[project.scripts]
rewardpilot = "rewardpilot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
